package mannus.newGui;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import mannus.core.AppCore;
import mannus.core.MyCalendar;

/**
 *
 * @author Kimjie
 */
public class NewJFrame extends javax.swing.JFrame {
    public AppCore app;
    
    /**
     * Creates new form NewJFrame
     * @param app
     */
    public NewJFrame(AppCore app) {
        this.app = app;
        initComponents();
    }
    //--------------------------------------------------------------------------------------------------------------------------------
    public void initializeWithData() {
        addYearsToBox(app.getSeasonsWithData()); //current year needs to be selected
        //2) addWeeksToBox(): adds all weeks with data (from the selected year) to the box, current week need to be selected and displayed
        updateBoxWeeks(MyCalendar.getWeeksOfOperatingYear(getSelectedYear(years_box))); //DA QUIIIIIIIIIIIIIIIIIIIIIIIIII
    }
    
    public void addYearsToBox(String[] str) {
        for(int i = 0 ; str != null && i < str.length; ++i) {
            addYearToBox(str[i]);
        }
    }
    
    public void addYearToBox(String str) {
        if(hasNotThisItem(years_box, str)) {
            years_box.addItem(str);
            //there is the need to order the components
        }
    }
    
    public boolean hasNotThisItem(JComboBox<String> box, String str) {
        int nItems = box.getItemCount();
            boolean found = false;
            
            for(int i = 0; i < nItems && !found; ++i) {
                if(box.getItemAt(i).equals(str))
                    found = true;
                }

        return !found;
    }
    //--------------------------------------------------------------------------------------------------------------------------------
    public void updateBoxWeeks(String[] weeks) {
        // TODO remove all items from the box, add new items
        weeks_box.removeAllItems​();
        fillBox(weeks_box, weeks); // TODO
        // TODO display on editor the week selected
    }
    
    private void fillBox(JComboBox<String> box, String[] itemsToAdd) {
        for(int i = 0; itemsToAdd != null && i < itemsToAdd.length; ++i) {
            box.addItem(itemsToAdd[i]);
        }
    }
    
    public String getSelectedYear(JComboBox<String> box) {
        return box.getItemAt(box.getSelectedIndex​());
    }
    //--------------------------------------------------------------------------------------------------------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        years_box = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        weeks_box = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tabGruppi = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("new Mannus JFrame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        years_box.setMaximumSize(null);
        years_box.setMinimumSize(new java.awt.Dimension(100, 30));
        years_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                years_boxActionPerformed(evt);
            }
        });

        jLabel1.setText("Anno");
        jLabel1.setMaximumSize(null);
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 30));

        weeks_box.setMaximumRowCount(30);
        weeks_box.setMaximumSize(null);
        weeks_box.setMinimumSize(new java.awt.Dimension(100, 30));

        jLabel2.setText("Settimana");
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 984, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        tabGruppi.addTab("Iscritti", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 984, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        tabGruppi.addTab("Attivita'", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 984, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        tabGruppi.addTab("Gruppi", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabGruppi)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(years_box, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weeks_box, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weeks_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(years_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(tabGruppi))
        );

        tabGruppi.getAccessibleContext().setAccessibleName("Gruppi");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void years_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_years_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_years_boxActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int i = JOptionPane.showConfirmDialog(null, "Desideri salvare i progressi?");
                switch(i) {
                    case 0: //YES
                        //save stuff DA FAREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
                        System.exit(0);
                        break;
                    case 1: //NO
                        //exit without saving DA FAREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
                        System.exit(0);
                        break;
                    case 2: //CANCEL
                        //keeps running
                        break;
                }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane tabGruppi;
    private javax.swing.JComboBox<String> weeks_box;
    private javax.swing.JComboBox<String> years_box;
    // End of variables declaration//GEN-END:variables
}
